name: Tests

on:
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: dart-lang/setup-dart@v1.4
        with:
          sdk: 3.0.3

      - name: Install dependencies
        run: dart pub get

      - name: Run tests
        run: dart test --reporter github

      - name: Dart Format
        run: |
          cd lib
          dart format . -o show --set-exit-if-changed

      - name: Check dart publish
        run: dart pub publish --dry-run

      - name: Verify tag version
        id: tag
        run: |
          export export TAG_VERSION=$(grep version pubspec.yaml |  awk -F  ': ' '{print $2}')
          echo "version=$TAG_VERSION" >> $GITHUB_OUTPUT

      - name: Confirm tag version
        run: echo ${{ steps.tag.outputs.version }}